# quiz_service.py - FINAL CORRECTED VERSION with gap-based exercise generation
import json
from datetime import date, timedelta
from db import db
from models import Gap, QuizResult, Question, UserQuestProgress, Quest, Exercise, UserExercise, Course
from sqlalchemy import func
from llm_generator import generate_exercise_for_gap

# ---------------------------
# Helper: create or get gaps course
# ---------------------------
def get_or_create_gaps_course():
    course = Course.query.filter_by(title="Gaps Exercises").first()
    if not course:
        course = Course(
            title="Gaps Exercises",
            description="Exercises generated by AI to reinforce your weak points",
            difficulty="mixed",
            tags="generated,ai"
        )
        db.session.add(course)
        db.session.commit()
    return course

def get_week_start():
    """Retourne le lundi de la semaine en cours."""
    today = date.today()
    return today - timedelta(days=today.weekday())

# ---------------------------
# QUEST PROGRESS HELPERS
# ---------------------------
def update_quest_progress(user_id, objective_type, increment=1):
    week_start = get_week_start()
    progresses = UserQuestProgress.query.join(Quest).filter(
        UserQuestProgress.user_id == user_id,
        UserQuestProgress.week_start_date == week_start,
        UserQuestProgress.completed == False,
        Quest.objective_type == objective_type
    ).all()
    for prog in progresses:
        prog.progress += increment
        if prog.progress >= prog.quest.objective_target:
            prog.completed = True
        db.session.add(prog)
    db.session.commit()

def get_weekly_quests(user_id):
    from helpers import get_week_start
    week_start = get_week_start()
    progresses = UserQuestProgress.query.join(Quest).filter(
        UserQuestProgress.user_id == user_id,
        UserQuestProgress.week_start_date == week_start
    ).all()
    return [{
        'id': p.id,
        'name': p.quest.name,
        'description': p.quest.description,
        'progress': p.progress,
        'target': p.quest.objective_target,
        'completed': p.completed,
        'claimed': p.claimed,
        'reward_gems': p.quest.reward_gems,
        'reward_xp': p.quest.reward_xp
    } for p in progresses]

def create_weekly_quests_for_user(user_id):
    from helpers import get_week_start
    week_start = get_week_start()
    existing = UserQuestProgress.query.filter_by(user_id=user_id, week_start_date=week_start).first()
    if existing:
        return
    quests = Quest.query.filter_by(is_weekly=True).all()
    if not quests:
        from helpers import init_default_quests
        init_default_quests()
        quests = Quest.query.filter_by(is_weekly=True).all()
    for quest in quests:
        prog = UserQuestProgress(user_id=user_id, quest_id=quest.id, week_start_date=week_start)
        db.session.add(prog)
    db.session.commit()

# ---------------------------
# QUIZ EVALUATION
# ---------------------------
def evaluate_quiz(user_id, quiz_id, answers):
    questions = Question.query.filter_by(quiz_id=quiz_id).all()
    if not questions:
        return {"score": 0, "gaps": []}
    
    total = len(questions)
    correct = 0
    concept_correct = {}
    concept_total = {}
    
    for q in questions:
        user_answer = answers.get(str(q.id))
        if user_answer and int(user_answer) == q.correct_option:
            correct += 1
            concept_correct[q.concept] = concept_correct.get(q.concept, 0) + 1
        concept_total[q.concept] = concept_total.get(q.concept, 0) + 1
    
    score = (correct / total) * 100
    
    xp_earned = correct * 5
    gems_earned = correct // 2
    from models import User
    user = User.query.get(user_id)
    user.total_xp = (user.total_xp or 0) + xp_earned
    user.gems = (user.gems or 0) + gems_earned
    
    # Mise à jour des gaps basée sur le taux de réussite par concept
    for concept, tot in concept_total.items():
        if concept is None:
            continue
        corr = concept_correct.get(concept, 0)
        success_rate = (corr / tot) * 100
        gap = Gap.query.filter_by(user_id=user_id, concept=concept).first()
        if not gap:
            gap = Gap(user_id=user_id, concept=concept, mastery_level=50.0)  # niveau initial à 50
            db.session.add(gap)
        if success_rate >= 70:
            # Réussite : +5 (max 100)
            gap.mastery_level = min(gap.mastery_level + 5, 100)
        elif success_rate < 50:
            # Échec : -10 (min 0)
            gap.mastery_level = max(gap.mastery_level - 10, 0)
        # Entre 50% et 70% -> pas de changement
        gap.last_updated = date.today()
    
    db.session.commit()
    
    # Détection des gaps pour l'affichage (ceux avec mastery_level < 50 ? ou comme avant ?)
    # On garde l'ancienne liste pour la réponse (concepts avec succès < 50% dans ce quiz)
    gaps_detected = []
    for concept, tot in concept_total.items():
        if concept is None:
            continue
        corr = concept_correct.get(concept, 0)
        if (corr / tot) < 0.5:
            gaps_detected.append(concept)
    
    result = QuizResult(
        user_id=user_id,
        quiz_id=quiz_id,
        score=score,
        answers_json=json.dumps(answers),
        gaps_json=json.dumps(gaps_detected)
    )
    db.session.add(result)
    db.session.commit()
    
    update_quest_progress(user_id, 'exercises', 1)
    update_quest_progress(user_id, 'xp', xp_earned)
    
    return {
        "score": score,
        "gaps": gaps_detected,
        "xp_earned": xp_earned,
        "gems_earned": gems_earned
    }

# ---------------------------
# EXERCISE GENERATION (based on student's gaps)
# ---------------------------
def get_gaps(user_id):
    gaps = Gap.query.filter_by(user_id=user_id).all()
    return [{"concept": g.concept, "level": g.mastery_level} for g in gaps]

def map_difficulty_to_xp(difficulty):
    mapping = {'easy': 20, 'medium': 30, 'hard': 40}
    return mapping.get(difficulty.lower(), 20)

def generate_personalized_exercises(user_id, limit=5, revision=False):
    if revision:
        completed_ids = [ue.exercise_id for ue in UserExercise.query.filter_by(user_id=user_id, completed=True).all()]
        exercises = Exercise.query.filter(Exercise.id.in_(completed_ids)).limit(limit).all()
        return [{
            "id": e.id,
            "question": e.question_text,
            "difficulty": e.difficulty,
            "xp_reward": e.xp_reward if hasattr(e, 'xp_reward') else map_difficulty_to_xp(e.difficulty)
        } for e in exercises]

    gaps = Gap.query.filter_by(user_id=user_id).all()
    if not gaps:
        exercises = Exercise.query.filter_by(difficulty='easy').limit(limit).all()
        return [{
            "id": e.id,
            "question": e.question_text,
            "difficulty": e.difficulty,
            "xp_reward": e.xp_reward if hasattr(e, 'xp_reward') else map_difficulty_to_xp(e.difficulty)
        } for e in exercises]

    gaps_course = get_or_create_gaps_course()
    new_exercises = []

    for gap in gaps[:limit]:
        existing = Exercise.query.filter(Exercise.tags.like(f'%{gap.concept}%')).first()
        if existing:
            new_exercises.append(existing)
            continue
        
        # Générer un nouvel exercice via Ollama
        gen_data = generate_exercise_for_gap(gap.concept, "medium")
        if gen_data:
            exercise = Exercise(
                course_id=gaps_course.id,
                question_text=gen_data['question'],
                correct_answer=gen_data['correct_answer'],
                explanation=gen_data.get('explanation', ''),
                difficulty=gen_data.get('difficulty', 'medium'),
                tags=gap.concept,
                xp_reward=map_difficulty_to_xp(gen_data.get('difficulty', 'medium'))
            )
            db.session.add(exercise)
            db.session.commit()
            new_exercises.append(exercise)
        else:
            fallback = Exercise.query.order_by(func.random()).first()
            if fallback:
                new_exercises.append(fallback)

        if len(new_exercises) >= limit:
            break

    if len(new_exercises) < limit:
        existing_ids = [e.id for e in new_exercises]
        remaining = limit - len(new_exercises)
        random_ex = Exercise.query.filter(Exercise.id.notin_(existing_ids)).limit(remaining).all()
        new_exercises.extend(random_ex)

    return [{
        "id": e.id,
        "question": e.question_text,
        "difficulty": e.difficulty,
        "xp_reward": e.xp_reward if hasattr(e, 'xp_reward') else map_difficulty_to_xp(e.difficulty)
    } for e in new_exercises]